spring:
  profiles:
    active: dev
  application:
    name: usercentre
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usercentre
    username: root
    password: hsp
  #Redis配置
  redis:
    port: 6379
    host: localhost
    database: 0
  #session失效时间（timeout单位 分钟）
  session:
    timeout: 86400
    store-type: redis
  # 解决springfox 3.0.x 版本 和 Spring Boot 2.6.x 版本冲突
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8080
  servlet:
    context-path: /api
# 关闭驼峰映射
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #全局逻辑删除
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
