server:
    port: 8081
    servlet:
        context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxx:3306/pro_project_test
    username: root
    password: xxx
  #Redis配置
  redis:
      port: 6379
      host: xxx
      database: 0
      password: xxx
      #session失效时间（timeout单位 分钟）
  session:
      timeout: 86400
      store-type: redis
  server:
    address: 0.0.0.0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl